"""
Django settings for HighConcurrence project.

Generated by 'django-admin startproject' using Django 1.11.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a*yzm&9v02o5_(#b%84+!ypnzd3em)1ml39o7uei-zx9$or#t-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sale',
    'order'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HighConcurrence.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HighConcurrence.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
MYSQLHOST = '192.168.177.126'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': MYSQLHOST,
        'PORT': '13308',
        'NAME': 'default',
        'USER': 'root',
        'PASSWORD': '12345678',
        'TEST': {
            'MIRROR': 'default'
        }
    },
    'sale': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': MYSQLHOST,
        'PORT': '13306',
        'NAME': 'sale',
        'USER': 'root',
        'PASSWORD': 'qq123456',
        'TEST': {
            'MIRROR': 'default'
        }
    },
    'order': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': MYSQLHOST,
        'PORT': '13307',
        'NAME': 'order',
        'USER': 'root',
        'PASSWORD': 'qq12345678',
        'TEST': {
            'MIRROR': 'default'
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

DATABASE_ROUTERS = ['HighConcurrence.DBRouter.DBAppsRouter']

RABBITHOST = '192.168.177.126'
RABBITPORT = 6673

REDISHOST = '192.168.177.126'
REDISPORT = 6380
REDISPW = 'qq123456'

REDIS = {
    'host': REDISHOST,
    'port': REDISPORT,
    'db': 0,
    'password': REDISPW
}
