# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-13 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='', max_length=500, verbose_name='商品名称')),
                ('status', models.CharField(default='正常', help_text='正常，删除，下架', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '商品信息',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='规格名称')),
                ('num', models.FloatField(default=0, verbose_name='库存')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('status', models.CharField(default='正常', help_text='正常，删除，下架', max_length=20, verbose_name='状态')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sale.SaleInfo', verbose_name='商品')),
            ],
            options={
                'verbose_name_plural': '规格型号',
                'ordering': ('-create_time',),
            },
        ),
    ]
